#!/bin/bash

export IMAGE_A=$(sed -n '1p' /tmp/.auth)
export IMAGE_B=$(sed -n '2p' /tmp/.auth)
export TAG=$(sed -n '3p' /tmp/.auth)
export PASS=$(sed -n '4p' /tmp/.auth)

docker login -u mak4dev -p $PASS
cd ~/proj-app && docker-compose up -d
